version: '3.8'

name: ctf_backend

services:
  mongodb:
    image: mongo:7.0.6
    container_name: ctf-database-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
      MONGO_INITDB_DATABASE: "${DB_NAME}"
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data:z

  # TODO:
  # redis:

env_file:
  - path: ../.env
    required: true
