name: ctf_backend

services:
  mongodb:
    image: docker.io/library/mongo:latest
    container_name: ctf-database-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
      MONGO_INITDB_DATABASE: "${DB_NAME}"
    ports:
      - "27017:27017"
    networks:
      fit-ctf-net: {}
    volumes:
      - mongo_data:/data/db:z

env_file:
  - path: ../.env
    required: true

volumes:
  mongo_data:

networks:
  fit-ctf-net: {}
